spring:
  datasource:
    url: jdbc:mysql://localhost:3344/weatherdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher