application:
  exceptions:
    NO_DATA_FOUND:
      code: "WEC_1000"
      detail: "No data found"
      status: 404
    BAD_REQUEST:
      code: "WEC_1001"
      detail: "Invalid user input"
      status: 400
    INTERNAL_ERROR:
      code: "WEC_2000"
      detail: "Unexpected system Interruption "
      status: 500
  api:
    title: WeatherApp API's
    version: 1.0.0-alpha
    description: API's to get weather related details for locations around the world.
    base-package: com.intuit.demo.weather
    contact-name: weatherapisupportgroup
    contact-email: weatherapisupportgroup@dt.com
    swagger:
      enable: true
spring:
  datasource:
    url: jdbc:mysql://mysqlsvr17.mysql.database.azure.com:3306/weatherdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: dhth
    password: demo@@2022
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none

server:
  servlet:
    context-path: /weather
management:
  endpoints:
    web:
      exposure:
        include: '*'

