insert into PUBLIC.TEMPERATURE (ID, LATITUDE, LOCATION, LONGITUDE, TEMPERATURE) values (1, '1', 'DUBLIN', '1.2', '55' );
insert into PUBLIC.TEMPERATURE (ID, LATITUDE, LOCATION, LONGITUDE, TEMPERATURE) values (2, '2', 'SJ', '2.2', '45' );
insert into PUBLIC.TEMPERATURE (ID, LATITUDE, LOCATION, LONGITUDE, TEMPERATURE) values (3, '3', 'CHENNAI', '3.808', '80' );
insert into PUBLIC.TEMPERATURE (ID, LATITUDE, LOCATION, LONGITUDE, TEMPERATURE) values (4, '4', 'PLEASANTON', '4.2', '40' );
insert into PUBLIC.TEMPERATURE (ID, LATITUDE, LOCATION, LONGITUDE, TEMPERATURE) values (5, '5.909', 'OAKLAND', '5.1212', '52' );